# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cowtech-extensions"
  s.version = "1.2.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shogun"]
  s.date = "2011-12-05"
  s.description = "Several Ruby object enhancements."
  s.email = "shogun_panda@me.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "cowtech-extensions.gemspec",
    "lib/cowtech-extensions.rb",
    "lib/cowtech-extensions/boolean.rb",
    "lib/cowtech-extensions/datetime.rb",
    "lib/cowtech-extensions/hash.rb",
    "lib/cowtech-extensions/math.rb",
    "lib/cowtech-extensions/object.rb",
    "lib/cowtech-extensions/pathname.rb",
    "lib/cowtech-extensions/string.rb",
    "lib/cowtech-extensions/version.rb"
  ]
  s.homepage = "http://github.com/ShogunPanda/cowtech-extensions"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Several Ruby object enhancements."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<actionpack>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<actionpack>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<actionpack>, [">= 0"])
  end
end

